name: pull_request

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["*"]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1

  Build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build App
        run: |
          xcodebuild \
          -workspace WaddleWallet.xcodeproj/project.xcworkspace \
          -scheme WaddleWallet \
          -sdk iphoneos \
          -destination "generic/platform=iOS" \
          CODE_SIGNING_ALLOWED=NO


      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro" \
            CODE_SIGNING_ALLOWED=NO
