name: pull_request

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["*"]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@4.2.0

  Build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod --version

      - name: Install Dependencies
        run: |
          cd GitHubActions
          pod install --repo-update

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Build App
        run: |
          cd GitHubActions
          xcodebuild build \
            -workspace GitHubActions.xcworkspace \
            -scheme GitHubActions \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO

      - name: Run Unit Tests
        run: |
          cd GitHubActions
          xcodebuild test \
            -workspace GitHubActions.xcworkspace \
            -scheme GitHubActions \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro" \
            CODE_SIGNING_ALLOWED=NO
